name: Build and Test Student Tracker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Run tests with Maven
      run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: test # Run after tests pass
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn install
    - name: Build Docker image
      run: docker build -t ghcr.io/lindokuhlekubeka/student-tracker:latest .
    - name: Push to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/lindokuhlekubeka/student-tracker:latest

permissions:
  contents: read
  packages: write # Needed for pushing to GitHub Container Registry
